external_components:
  - source:
      type: git
      url: https://github.com/konstantint/esphome_i18n_component
    components: [i18n]

esphome:
  includes:
    - i18n_helper.h

i18n:
  sources:
    - ../translations/de.yaml
    - ../translations/en.yaml
    - ../translations/ru.yaml

select:
  - platform: lvgl
    widget: lvgl_language_dropdown
    name: Language
    id: language_selector
    entity_category: config
    internal: true
    restore_value: true
    on_value:
      then:
        - lambda: |-
            set_locale(x.c_str());
            i18n_helper.update_translations();
